# Generated by Django 4.1.6 on 2023-02-13 18:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_post_user_product_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_h1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('blog_annotation', models.CharField(blank=True, help_text='максимальное количество символов - 150', max_length=150, null=True, verbose_name='Аннотация')),
                ('title', models.CharField(blank=True, max_length=70, null=True, verbose_name='Метатэг Title')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Содержание')),
                ('meta_description', models.CharField(blank=True, help_text='максимальное количество символов - 300', max_length=300, null=True, verbose_name='Метатэг Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='максимальное количество символов - 150', max_length=150, null=True, verbose_name='Метатег Keywords')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блог',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts_h1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок')),
                ('title', models.CharField(blank=True, max_length=70, null=True, verbose_name='Метатэг Title')),
                ('official_company_name', models.CharField(blank=True, help_text='максимальное количество символов - 30', max_length=30, null=True, verbose_name='Юридическое название')),
                ('country', models.CharField(blank=True, help_text='максимальное количество символов - 20', max_length=20, null=True, verbose_name='Страна')),
                ('itin', models.CharField(blank=True, help_text='максимальное количество символов - 20', max_length=20, null=True, verbose_name='ИНН')),
                ('address', models.CharField(blank=True, help_text='максимальное количество символов - 50', max_length=50, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, help_text='максимальное количество символов - 30', max_length=30, null=True, verbose_name='Телефон')),
                ('email', models.CharField(blank=True, help_text='максимальное количество символов - 20', max_length=20, null=True, verbose_name='Email')),
                ('meta_description', models.CharField(blank=True, help_text='максимальное количество символов - 300', max_length=300, null=True, verbose_name='Метатэг Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='максимальное количество символов - 150', max_length=150, null=True, verbose_name='Метатег Keywords')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_h1', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('home_annotation', models.CharField(help_text='максимальное количество символов - 150', max_length=150, verbose_name='Аннотация')),
                ('title', models.CharField(help_text='максимальное количество символов - 70', max_length=70, verbose_name='Метатэг Title')),
                ('description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Содержание')),
                ('meta_description', models.CharField(blank=True, help_text='максимальное количество символов - 300', max_length=300, null=True, verbose_name='Метатэг description')),
                ('meta_keywords', models.CharField(blank=True, help_text='максимальное количество символов - 150', max_length=150, null=True, verbose_name='Метатег Keywords')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.RemoveField(
            model_name='category',
            name='none_posts',
        ),
        migrations.RemoveField(
            model_name='category',
            name='none_products',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='meta_title',
        ),
        migrations.AddField(
            model_name='category',
            name='add_new_prod',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата добавления последнего продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='absolute_top',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Позиция в топе'),
        ),
        migrations.AddField(
            model_name='product',
            name='change_range_prod',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Рейтинг изменен'),
        ),
        migrations.AddField(
            model_name='product',
            name='confirm_update_range',
            field=models.CharField(choices=[('true', 'ДА'), ('false', 'НЕТ')], default='true', max_length=10, verbose_name='Поднять продукт в ТОП?'),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_annotation',
            field=models.CharField(blank=True, help_text='максимальное количество символов - 150', max_length=150, null=True, verbose_name='Аннотация - выводится в карточке продукта'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('опубликовано', 'ДА'), ('не опубликовано', 'НЕТ')], default='опубликовано', max_length=20, verbose_name='Публиковать?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='annotation_for_posts',
            field=models.CharField(blank=True, help_text='максимальное количество символов - 200', max_length=200, null=True, verbose_name='Аннотация для блога'),
        ),
        migrations.AlterField(
            model_name='category',
            name='annotation_for_products',
            field=models.CharField(blank=True, help_text='максимальное количество символов - 200', max_length=200, null=True, verbose_name='Аннотация для продуктов'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(db_index=True, help_text='Выбирайте наименование тщательно - от него формируется ссылка и его нельзя будет изменить, максимальное количество символов - 30', max_length=30, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_for_posts',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Полное описание для блога'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_for_products',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Полное описание для продуктов'),
        ),
        migrations.AlterField(
            model_name='post',
            name='change_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, help_text='рекомендуемый размер - 2000*1000', null=True, upload_to='posts/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, help_text='максимальное количество символов - 100', max_length=100, unique=True, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, help_text='рекомендуемый размер - 2000*1000', null=True, upload_to='products/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(db_index=True, help_text='максимальное количество символов - 90', max_length=90, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=90, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='version',
            name='value',
            field=models.CharField(help_text='максимальное количество символов - 10', max_length=10, verbose_name='Номер версии'),
        ),
    ]
