# Generated by Django 4.1.6 on 2023-02-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_blog_contacts_home_remove_category_none_posts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_h1_for_posts',
            field=models.CharField(blank=True, help_text='максимальное количество символов - 70', max_length=70, null=True, verbose_name='Заголовк H1 для блога'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_h1_for_products',
            field=models.CharField(blank=True, help_text='максимальное количество символов - 70', max_length=70, null=True, verbose_name='Заголовк H1 для продуктов'),
        ),
        migrations.AlterField(
            model_name='category',
            name='keywords_for_posts',
            field=models.CharField(blank=True, help_text='максимальное количество символов - 150', max_length=150, null=True, verbose_name='Keywords для блога'),
        ),
        migrations.AlterField(
            model_name='category',
            name='keywords_for_products',
            field=models.CharField(blank=True, help_text='максимальное количество символов - 150', max_length=150, null=True, verbose_name='Keywords для продуктов'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description_for_posts',
            field=models.CharField(blank=True, help_text='максимальное количество символов - 300', max_length=300, null=True, verbose_name='Description для блога'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_description_for_products',
            field=models.CharField(blank=True, help_text='максимальное количество символов - 300', max_length=300, null=True, verbose_name='Description для продуктов'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title_for_posts',
            field=models.CharField(blank=True, help_text='максимальное количество символов - 70', max_length=70, null=True, verbose_name='Title для блога'),
        ),
        migrations.AlterField(
            model_name='category',
            name='meta_title_for_products',
            field=models.CharField(blank=True, help_text='максимальное количество символов - 70', max_length=70, null=True, verbose_name='Title для продуктов'),
        ),
        migrations.AlterField(
            model_name='post',
            name='banned',
            field=models.CharField(choices=[('заблокировано модератором', 'ЗАБАНИТЬ'), ('одобрено модератором', 'РАЗБАНИТЬ')], default='одобрено модератором', max_length=30, verbose_name='Забанить пост?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='banned',
            field=models.CharField(choices=[('заблокировано модератором', 'ЗАБАНИТЬ'), ('одобрено модератором', 'РАЗБАНИТЬ')], default='одобрено модератором', max_length=30, verbose_name='Забанить продукт?'),
        ),
    ]
