# Generated by Django 4.1.6 on 2023-02-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_blog_blog_annotation_alter_blog_blog_h1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_annotation',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='version',
            name='description',
            field=models.CharField(help_text='До 250 символов', max_length=250, verbose_name='Улучшения'),
        ),
        migrations.AlterField(
            model_name='version',
            name='status',
            field=models.CharField(choices=[('активно', 'ДА'), ('неактивно', 'НЕТ')], default='неактивно', max_length=10, verbose_name='Релиз?'),
        ),
    ]
