# Generated by Django 4.1.6 on 2023-02-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_prod_annotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_annotation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Аннотация'),
        ),
        migrations.AlterField(
            model_name='version',
            name='value',
            field=models.CharField(max_length=10, verbose_name='№'),
        ),
    ]
