# Generated by Django 4.1.7 on 2023-02-27 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_product_prod_annotation_alter_version_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.CharField(blank=True, help_text='До 40 символов', max_length=40, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='version',
            name='status',
            field=models.CharField(choices=[('активно', 'ДА'), ('неактивно', 'НЕТ')], default='неактивно', max_length=10, verbose_name='Релиз'),
        ),
    ]
